### ISSUE TITLE
Feature:  add background colour yellow 

### ISSUE THREAD

**Issue by PRITAM-TU** [rajdeepchakraborty-rc/School-Carnival-2K24#29]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

add background colour 

### Screenshots/Videos(if applicable)

![image](https://github.com/user-attachments/assets/e5d9baa2-a793-462a-b900-8c647d686971)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by rajdeepchakraborty-rc** [comment]
## **NOTE:** Theme should be : **ORANGE & YELLOW**

**Comment by rajdeepchakraborty-rc** [comment]
### UI work PR has already been linked & merged.
